import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div>
          <header className="bg-white shadow fixed w-full z-10">
            <nav className="flex justify-between items-center p-4">
              <Link href="/" className="text-2xl font-bold">
                DARWISH
              </Link>
              <div className="flex space-x-4">
                <Link
                  href="/swift-dev"
                  className="text-gray-700 hover:text-black"
                >
                  Swift
                </Link>
                <Link href="/python" className="text-gray-700 hover:text-black">
                  Python
                </Link>
                <Link href="/rust" className="text-gray-700 hover:text-black">
                  Rust
                </Link>
                <Link
                  href="/english"
                  className="text-gray-700 hover:text-black"
                >
                  English
                </Link>
              </div>
            </nav>
          </header>
          <main className="pt-16">{children}</main>
        </div>
      </body>
    </html>
  );
}
